### ISSUE TITLE
Ingame and button inputs

### ISSUE THREAD

**Issue by TabbHonmin** [zitron-git/KSPSerialIO#17]
If I clic on the RCS ingame button, it turns on of course, but then I can no longer use the arduino button to turn it on/off. And if I clic on it again, it turns off, and then I can use the arduino button again to control it.

Made a short video to show you what it does : https://www.youtube.com/watch?v=K3OvMLiDWco

I think this comes from the following lines (starting at 1081) :

`if (KSPSerialPort.VControls.RCS != KSPSerialPort.VControlsOld.RCS)
{
ActiveVessel.ActionGroups.SetGroup(KSPActionGroup.RCS, KSPSerialPort.VControls.RCS);
KSPSerialPort.VControlsOld.RCS = KSPSerialPort.VControls.RCS;
//ScreenMessages.PostScreenMessage("RCS: " + KSPSerialPort.VControls.RCS.ToString(), 10f, KSPIOScreenStyle);
}`

**Comment by hugopeeters** [comment]
I edited out the if-statement in my fork in the hybrid-control branch. It just needs compiling. https://github.com/hugopeeters/KSPSerialIO/tree/hybrid-control

**Comment by TabbHonmin** [comment]
> 
> 
> I edited out the if-statement in my fork in the hybrid-control branch. It just needs compiling. https://github.com/hugopeeters/KSPSerialIO/tree/hybrid-control

Unfortunately I don't have Visual Studio to do it myself.

**Comment by zitron-git** [comment]
The problem is if you just remove the if statements you will be sending action group commands to KSP every frame, even if they have not changed. This may or may not cause problems.

**Comment by hugopeeters** [comment]
So, the best way would be to implement the check for change in button state AND change in in-game state in the plugin code! We tried implementing that check in the Arduino code, but we do indeed see issues.

**Comment by zitron-git** [comment]
I don't think you need to do anything in plugin code. Are you able to check the RCS status bit in NavballSASMode sent from KSP? How are you toggling the output bit in arduino?

**Comment by hugopeeters** [comment]
I'm thinking we need to update the if-statement to this:
`if (KSPSerialPort.VControls.RCS != KSPSerialPort.VControlsOld.RCS || KSPSerialPort.VControls.RCS != ActiveVessel.ActionGroups[KSPActionGroup.RCS])`

**Comment by zitron-git** [comment]
Wouldn't that just overwrite the in game UI? You click on navball but nothing happens because it's immediately overwritten by the arduino input.

**Comment by hugopeeters** [comment]
Ah, right. Too quick on my part. What if we keep track of the previous in-game state in a variable. Then when we see that change (by controlling the RCS in-game with the mouse), we can set both SPSerialPort.VControls.RCS and KSPSerialPort.VControlsOld.RCS equal to the new value.

**Comment by hugopeeters** [comment]
Thinking through this some more... Shouldn't the plugin code just toggle the RCS (off->on, on->off) each time the button input goes from low to high?
The current code assumes an unbiased switch (one that remains in the ON state until you press it again). For momentary switches, each press of the switch should toggle the state (state = !state).

**Comment by zitron-git** [comment]
Yes, so you just need to write some simple arduino code to make your momentary switch toggle NavballSASMode.

**Comment by hugopeeters** [comment]
I think you mean RCS instead of NavballSASMode?
No, the current plugin code explicitly sets the RCS to the state of the button, when a change in the button is received, independent of what the current state of RCS is. That is okay for toggle switches. 
For a momentary button however, you want the RCS to toggle every time the button is briefly pressed. That cannot be coded in the Arduino using the current code in the plugin. I have sent an updated plugin to TabbHonmin for testing. The only change is this is how the RCS gets set: `ActiveVessel.ActionGroups.SetGroup(KSPActionGroup.RCS, !ActiveVessel.ActionGroups[KSPActionGroup.RCS]);`

**Comment by hugopeeters** [comment]
Actually, I also changed the if-statement to trigger on the leading edge only, instead of on each state change: `if (KSPSerialPort.VControls.RCS && !KSPSerialPort.VControlsOld.RCS)`

The Arduino code can then just send the current state of the button.

**Comment by TabbHonmin** [comment]
I'm using pushbuttons for various vessel actions, but also some switches. So, as I don't know how to change and compile the plugin, I would prefer the arduino code to handle most of actions and checks.
So that I can code every type of controls regardless of the plugin.

**Comment by zitron-git** [comment]
Can't you just uses this arduino code?

if (digitalRead(RCSPIN) != RCSPIN_Old) {
	if (ControlStatus(AGRCS) == 1)
		MainControls(RCS, LOW);
	else
		MainControls(RCS, HIGH);

	RCSPIN_Old = digitalRead(RCSPIN);
}

**Comment by TabbHonmin** [comment]
With hugopeeters modified plugin it's not working. When I press the pushbutton, RCS activates, but then the pushbutton has no more effect. However I can control RCS by clicing on it.

**Comment by hugopeeters** [comment]
> Can't you just uses this arduino code?

I'll do some testing tomorrow. Thanks.

**Comment by hugopeeters** [comment]
> With hugopeeters modified plugin it's not working. When I press the pushbutton, RCS activates, but then the pushbutton has no more effect. However I can control RCS by clicing on it.

Please try with updated version from me. I moved setting the old value out of the if-statement. That explains why it stops working after pushing the button once.

**Comment by TabbHonmin** [comment]
Ok let me try right now.
I will edit this answer to tell you how it went.

**Comment by TabbHonmin** [comment]
I'm still working on my setup. I think I know which command will be controlled by pushbuttons and which ones will be controlled by switches. But this could change.
So I may need to do the same you did on other controls (SAS, lights, gears, ...).

If it is not too much asking, could you tell me what I need to install with Visual Studio to be able to make my own modification on the plugin and compile it myself ?

**Comment by hugopeeters** [comment]
> It is working ! Good job !

Hah! Nice! Very happy about that.

**Comment by hugopeeters** [comment]
> If it is not too much asking, could you tell me what I need to install with Visual Studio to be able to make my own modification on the plugin and compile it myself ?

I'm no developer, so my methods might be a complete hack and not give you the same results as me, but here's what I did. I cloned the KSPserialIO repository. Downloaded Visual Studio (community edition should be available for free), select CSharp/.NET if you get any selection screens. Open the .csproj file. Edit the KSPIO.cs file how you see fit. Fix errors (red icons) under references by copying the dll files from my includes folder here https://github.com/hugopeeters/KSPSerialIO/tree/master/Includes (I needed at least Assembly-CSharp.dll, UnityEngine.dll and UnityEngine.UI.dll). Add these files as references by right-clicking references, edit references, .Net Assembly tab, browse to the dll files. Remove the references with the errors. Now in the menu bar select Release instead of Debug and press Build (hammer icon). If there are no errors, you get some new files in the /bin/release folder. Copy those into your plugin, overwriting the old files. Fingers crossed and hope for the best.

**Comment by hugopeeters** [comment]
> Can't you just uses this arduino code?
> 
> ```
> byte RCSPIN_Old;
> 
> if (digitalRead(RCSPIN) != RCSPIN_Old) {
> 	if (ControlStatus(AGRCS) == 1)
> 		MainControls(RCS, LOW);
> 	else
> 		MainControls(RCS, HIGH);
> 
> 	RCSPIN_Old = digitalRead(RCSPIN);
> }
> ```

We actually did try something similar to what you are suggesting (there are some differences in the code, like only triggering on the press, not the release), but found that it works about 1 in 10 pushes of the button. Not sure what the cause of that is.

**Comment by TabbHonmin** [comment]
I think I managed to add the references and I will be able to compile my own plugin.
However, can you show me how exactly you updated the plugin code for RCS and SAS ? I couldn't find a readable file in your fix.

**Comment by hugopeeters** [comment]
`                    if (KSPSerialPort.VControls.RCS && !KSPSerialPort.VControlsOld.RCS)
                    {
                        ActiveVessel.ActionGroups.SetGroup(KSPActionGroup.RCS, !ActiveVessel.ActionGroups[KSPActionGroup.RCS]);
                        //ScreenMessages.PostScreenMessage("RCS: " + KSPSerialPort.VControls.RCS.ToString(), 10f, KSPIOScreenStyle);
                    }
                    KSPSerialPort.VControlsOld.RCS = KSPSerialPort.VControls.RCS;`

**Comment by TabbHonmin** [comment]
Weird. I did that in the plugin, and I don't get the same result than with your fix.
The clic works well, but the RSC are on when the pushbutton is pressed, and off when it is released.

**Comment by hugopeeters** [comment]
Are you sure you have
```C#
if (KSPSerialPort.VControls.RCS && !KSPSerialPort.VControlsOld.RCS) {
```
and not
```C#
if (KSPSerialPort.VControls.RCS != KSPSerialPort.VControlsOld.RCS) {
```

**Comment by hugopeeters** [comment]
If it helps, I have published my own edited version of the source code in the hybrid-control branch on my [github](https://github.com/hugopeeters/KSPSerialIO/tree/hybrid-control)

**Comment by TabbHonmin** [comment]
Yep I took your code and now it works like a charm.
You rock man !

**Comment by TabbHonmin** [comment]
I'm now working on the SAS modes. I'm experiencing the same issue. Once I clic on the SAS or on any SAS mode, I can't control it again with the pushbutton.

I updated the plugin code like this : 
`if (KSPSerialPort.VControls.SASMode != KSPSerialPort.VControlsOld.SASMode)
                    {
                        if (KSPSerialPort.VControls.SASMode != 0 && KSPSerialPort.VControls.SASMode < 11)
                        {
                            if (!ActiveVessel.Autopilot.CanSetMode((VesselAutopilot.AutopilotMode)(KSPSerialPort.VControls.SASMode - 1)))
                            {
                                ScreenMessages.PostScreenMessage("KSPSerialIO: SAS mode " + KSPSerialPort.VControls.SASMode.ToString() + " not avalible");
                            }
                            else
                            {
                                ActiveVessel.Autopilot.SetMode((VesselAutopilot.AutopilotMode)KSPSerialPort.VControls.SASMode - 1);
                            }
                        }
                        //KSPSerialPort.VControlsOld.SASMode = KSPSerialPort.VControls.SASMode;
                    }
                    KSPSerialPort.VControlsOld.SASMode = KSPSerialPort.VControls.SASMode;`

with arduino code : 
`if (!digitalRead(PROGRADEPIN) && ControlStatus(AGSAS) == 1) {
      setSASMode(SMPrograde); //setting SAS mode
    }`

No luck.

**Comment by hugopeeters** [comment]
Did you also update the part right after the RCS code?
```C#
                    //if (ActiveVessel.ctrlState.killRot != KSPSerialPort.VControls.SAS)
                    if (KSPSerialPort.VControls.SAS && !KSPSerialPort.VControlsOld.SAS)
                    {
                        ActiveVessel.ActionGroups.SetGroup(KSPActionGroup.SAS, !ActiveVessel.ActionGroups[KSPActionGroup.SAS]);
                        //ScreenMessages.PostScreenMessage("SAS: " + KSPSerialPort.VControls.SAS.ToString(), 10f, KSPIOScreenStyle);
                    }
                        KSPSerialPort.VControlsOld.SAS = KSPSerialPort.VControls.SAS;
```

**Comment by TabbHonmin** [comment]
Yes I did. Turning SAS on and off works perfectly with both pushbutton and clicing. Just like RCS.
What doesn't work is the SAS mode selection.

**Comment by hugopeeters** [comment]
Ok. So instead of checking: is the button sending a different value now than before, we should check: is the button trying to set the SASmode to something different than it is now in-game. Because now, if you change the in-game state, the button no longer works, because the plugin says: I'll ignore that button because it sent the same request before.

I think this is how that should work, but I'm not sure the data format is identical:
```C#
if (KSPSerialPort.VControls.SASMode != KSPSerialPort.VData.NavballSASMode)
```

**Comment by TabbHonmin** [comment]
> ```cs
> if (KSPSerialPort.VControls.SASMode != KSPSerialPort.VData.NavballSASMode)
> ```
No, this broke the plugin.
Shouldn't we compare `KSPSerialPort.VControls.SASMode` to first 4 bites of `KSPSerialPort.VData.NavballSASMode` ?

**Comment by hugopeeters** [comment]
Something like that, yes. I don't have to opportunity to debug now. You can add some screen messages in the plugin code to compare the values and figure out how to properly compare them.

**Comment by TabbHonmin** [comment]
I know some coding and I'm doing my best to manage that. But I think this is near my skills limit.
I have no clue how to debug this.

**Comment by TabbHonmin** [comment]
I made some tests. Unlike others on/off systems, I can't simply detect a pushbutton and then set the system to the opposite as it was before.
I have to set the SAS to one of the modes (prograde, retrograde, etc...) when pushbutton is pressed.

**Comment by TabbHonmin** [comment]
I finally solved this today with the following arduino code.
I store SAS mode in a variable (privateSASmode). So that if another mode have been selected by mouse clic I know it.
Then I check if pushbuttons have been pressed. If yes, I store the related mode in the same variable and set the SAS mode ingame.
Finally, if it has been more than 0.5 sec since the last pushbutton press, I set the ingame SAS mode according to the variable.


`privateSASmode = getSASMode();

    if (!digitalRead(STABILITYPIN) && ControlStatus(AGSAS) == 1) {
      privateSASmode = 1;
      setSASMode(privateSASmode); //setting SAS mode
      SASchangeOld = now;
    }

    if (!digitalRead(PROGRADEPIN) && ControlStatus(AGSAS) == 1) {
      privateSASmode = 2;
      setSASMode(privateSASmode); //setting SAS mode
      SASchangeOld = now;
    }

    if (!digitalRead(RETROGRADEPIN) && ControlStatus(AGSAS) == 1) {
      privateSASmode = 3;
      setSASMode(privateSASmode); //setting SAS mode
      SASchangeOld = now;
    }

    if (!digitalRead(MANEUVERPIN) && ControlStatus(AGSAS) == 1) {
      privateSASmode = 10;
      setSASMode(privateSASmode); //setting SAS mode
      SASchangeOld = now;
    }

    if (now - SASchangeOld > 500) {
      setSASMode(privateSASmode); //setting SAS mode
    }`
