### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by nkappler** [zitron-git/KSPSerialIO#18]
It is not clear to me how to install this mod and there doesn't seem to be any documentation

**Comment by zitron-git** [comment]
Same as any other mod? Have you ever installed a mod for KSP?

**Comment by nkappler** [comment]
Yes, I did and I tried that way, however I could not get the serial connection working.
It seemed to me that the mod would not load.
Do you have a way to connect to it with puTTY for example?
Or are there any log files I could check?

**Comment by zitron-git** [comment]
The logs are just in the normal KSP log? This is used to communicate through physical serial ports so you can talk to an arduino. Did you check the ksp forum thread?

**Comment by nkappler** [comment]
ok thanks. I'll have a look at the forum
