### ISSUE TITLE
VesselData.MNDeltaV

### ISSUE THREAD

**Issue by MrOnak** [zitron-git/KSPSerialIO#7]
The VesselData.MNDeltaV member displays the total amount of deltaV required for a maneuver node.

Is this on purpose? I believe _remaining_ deltaV for a maneuver node will be much more useful.

In relation to that, there doesn't seem to be a member "MNDuration" or something like that which contains the seconds required to execute a maneuver node. Is something like that planned?

**Comment by zitron-git** [comment]
It's not possible to get the remaining deltav from patchedConicSolver.maneuverNodes. Might need to steal some code again...

**Comment by MrOnak** [comment]
Oh... okay... hmm. That's sad. Just thought I'd mention it.

**Comment by zitron-git** [comment]
VesselData.MNDeltaV now shows deltaV remaining in the latest version
